### PR TITLE
Revert "Pass GITHUB_AUTH_TOKEN into jx-release-version"

### PR DESCRIPTION
**Pull request by rawlingsj**
Reverts jenkins-x/draft-packs#45

Sorry - I'm going to need to revert this.  I think all that was needed was the jx-release-version has to happen after `sh "jx step git credentials"`.  Reverting and will merge the preferred way asap.

### CODE REVIEW

**Comment by liyihe96** [comment]
Hey @rawlingsj, should we still keep DIGEST_HEX instead of TAG for devpod?

**Comment by rawlingsj** [comment]
@liyihe96 hi - yeah I forgot that was in the PR too, we probably need to submit a new PR with just that change.  Would you mind doing that?  If not I'll try and get to it later today.

**Comment by robocoder99** [comment]
Ah well whoops. Got carried away. Didn't look like it was passing that environmental variable in though. Sorry about that. That was my personal hotfix and I figured I'd throw up an issue / PR to draw attention to the problem / potential solution.

**Comment by robocoder99** [comment]
I will create a new PR for just that change if it is still wanted. Would you also like me to open one with the fixed ordering, I don't see one in yet? (I'll test it out on my environment before doing anything though just to be certain) @rawlingsj

**Pull request merged**
